import os
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL


# -------------------------
# 1. Project paths
# -------------------------
project_root = Path(__file__).resolve().parent.parent

csv_path = (
    project_root
    / "data"
    / "cleaned"
    / "online_retail_cleaned.csv"
)

env_path = project_root / ".env"


# -------------------------
# 2. Load environment variables
# -------------------------
load_dotenv(env_path, override=True)

db_url = URL.create(
    drivername="mysql+pymysql",
    username=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST"),
    port=int(os.getenv("DB_PORT")),
    database=os.getenv("DB_NAME")
)

engine = create_engine(
    db_url,
    pool_pre_ping=True
)


# -------------------------
# 3. Read cleaned dataset
# -------------------------
df = pd.read_csv(csv_path)

# Make sure row_id is generated by MySQL,
# not loaded from the CSV
if "row_id" in df.columns:
    df = df.drop(columns=["row_id"])

print(f"Loaded {len(df):,} cleaned rows.")


# -------------------------
# 4. Recreate table with primary key
# -------------------------
create_table_query = """
CREATE TABLE retail_sales (
    row_id BIGINT NOT NULL AUTO_INCREMENT,
    InvoiceNo BIGINT,
    StockCode TEXT,
    Description TEXT,
    Quantity BIGINT,
    InvoiceDate TEXT,
    UnitPrice DOUBLE,
    CustomerID BIGINT,
    Country TEXT,
    TotalPrice DOUBLE,
    PRIMARY KEY (row_id)
);
"""

with engine.begin() as connection:
    connection.execute(
        text("DROP TABLE IF EXISTS retail_sales;")
    )

    connection.execute(
        text(create_table_query)
    )


# -------------------------
# 5. Load cleaned data
# -------------------------
df.to_sql(
    name="retail_sales",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=5000
)
